import { Meal } from "@/types";

export const MEAL_LIBRARY: Meal[] = [
  // HIGH PROTEIN
  {
    id: "hp-1",
    name: "Grilled Chicken & Quinoa Bowl",
    category: "high-protein",
    calories: 520,
    protein: 48,
    carbs: 42,
    fat: 12,
    prepTime: 25,
    imageQuery: "chicken",
    ingredients: ["200g chicken breast", "1 cup quinoa", "1 cup broccoli", "2 tbsp olive oil", "garlic", "lemon"],
    instructions: [
      "Cook quinoa in chicken broth for extra flavor.",
      "Season chicken with garlic, salt, pepper, and lemon zest.",
      "Grill chicken 6 min per side until cooked through.",
      "Steam broccoli 4 minutes.",
      "Assemble bowl and drizzle with olive oil.",
    ],
  },
  {
    id: "hp-2",
    name: "Egg White & Turkey Scramble",
    category: "high-protein",
    calories: 380,
    protein: 42,
    carbs: 8,
    fat: 18,
    prepTime: 10,
    imageQuery: "omelette",
    ingredients: ["6 egg whites", "100g ground turkey", "1 cup spinach", "½ onion", "1 tsp olive oil", "salt & pepper"],
    instructions: [
      "Brown turkey in a pan over medium heat.",
      "Add diced onion and cook 3 minutes.",
      "Add spinach and wilt.",
      "Pour in egg whites and scramble until cooked.",
      "Season and serve.",
    ],
  },
  {
    id: "hp-3",
    name: "Greek Yogurt Protein Bowl",
    category: "high-protein",
    calories: 340,
    protein: 32,
    carbs: 38,
    fat: 6,
    prepTime: 5,
    imageQuery: "yogurt",
    ingredients: ["1 cup plain Greek yogurt (2%)", "1 scoop protein powder", "½ cup blueberries", "2 tbsp granola", "1 tbsp honey"],
    instructions: [
      "Mix yogurt and protein powder until smooth.",
      "Top with blueberries and granola.",
      "Drizzle with honey.",
    ],
  },
  {
    id: "hp-4",
    name: "Tuna Avocado Wrap",
    category: "high-protein",
    calories: 440,
    protein: 38,
    carbs: 30,
    fat: 18,
    prepTime: 10,
    imageQuery: "tuna",
    ingredients: ["1 can tuna (drained)", "½ avocado", "1 whole wheat wrap", "lettuce", "tomato", "lemon juice", "salt & pepper"],
    instructions: [
      "Mix tuna with mashed avocado and lemon juice.",
      "Season with salt and pepper.",
      "Layer onto wrap with lettuce and tomato.",
      "Roll tightly and serve.",
    ],
  },
  // HIGH CARB
  {
    id: "hc-1",
    name: "Oat & Banana Power Pancakes",
    category: "high-carb",
    calories: 480,
    protein: 14,
    carbs: 88,
    fat: 8,
    prepTime: 15,
    imageQuery: "pancakes",
    ingredients: ["1 cup rolled oats", "1 banana", "2 eggs", "½ cup milk", "1 tsp baking powder", "maple syrup"],
    instructions: [
      "Blend oats into flour.",
      "Mix with mashed banana, eggs, milk, and baking powder.",
      "Cook on a non-stick pan over medium heat, 2 min per side.",
      "Serve with maple syrup.",
    ],
  },
  {
    id: "hc-2",
    name: "Sweet Potato & Black Bean Bowl",
    category: "high-carb",
    calories: 520,
    protein: 16,
    carbs: 92,
    fat: 10,
    prepTime: 30,
    imageQuery: "sweet potato",
    ingredients: ["2 medium sweet potatoes", "1 can black beans", "1 cup brown rice", "cumin", "chili powder", "lime", "sour cream"],
    instructions: [
      "Roast cubed sweet potatoes at 400°F for 25 minutes.",
      "Cook rice per package directions.",
      "Warm black beans with cumin and chili powder.",
      "Assemble bowl and finish with lime juice and sour cream.",
    ],
  },
  {
    id: "hc-3",
    name: "Whole Grain Pasta Primavera",
    category: "high-carb",
    calories: 560,
    protein: 18,
    carbs: 96,
    fat: 12,
    prepTime: 20,
    imageQuery: "pasta",
    ingredients: ["200g whole grain pasta", "zucchini", "cherry tomatoes", "bell pepper", "garlic", "olive oil", "parmesan"],
    instructions: [
      "Cook pasta al dente.",
      "Sauté garlic and vegetables in olive oil 5 minutes.",
      "Toss with pasta and top with parmesan.",
    ],
  },
  // LOW CALORIE
  {
    id: "lc-1",
    name: "Zucchini Noodle Stir Fry",
    category: "low-calorie",
    calories: 220,
    protein: 18,
    carbs: 14,
    fat: 8,
    prepTime: 15,
    imageQuery: "stir fry",
    ingredients: ["2 zucchinis (spiralized)", "100g shrimp", "soy sauce", "ginger", "garlic", "sesame oil", "green onion"],
    instructions: [
      "Sauté garlic and ginger in sesame oil.",
      "Add shrimp and cook 3 minutes.",
      "Add zucchini noodles and soy sauce, toss 2 minutes.",
      "Top with green onion.",
    ],
  },
  {
    id: "lc-2",
    name: "Chicken Lettuce Wraps",
    category: "low-calorie",
    calories: 280,
    protein: 32,
    carbs: 10,
    fat: 10,
    prepTime: 15,
    imageQuery: "chicken",
    ingredients: ["200g ground chicken", "butter lettuce leaves", "water chestnuts", "hoisin sauce", "soy sauce", "ginger", "garlic"],
    instructions: [
      "Cook ground chicken with garlic and ginger.",
      "Add diced water chestnuts, hoisin, and soy sauce.",
      "Spoon into lettuce cups and serve.",
    ],
  },
  {
    id: "lc-3",
    name: "Tomato Lentil Soup",
    category: "low-calorie",
    calories: 260,
    protein: 14,
    carbs: 44,
    fat: 4,
    prepTime: 35,
    imageQuery: "lentil soup",
    ingredients: ["1 cup red lentils", "1 can diced tomatoes", "onion", "carrot", "celery", "cumin", "vegetable broth"],
    instructions: [
      "Sauté onion, carrot, and celery 5 minutes.",
      "Add lentils, tomatoes, broth, and cumin.",
      "Simmer 25 minutes until lentils are soft.",
      "Blend half the soup for a creamy texture.",
    ],
  },
  // BALANCED
  {
    id: "bal-1",
    name: "Salmon & Roasted Veggie Plate",
    category: "balanced",
    calories: 490,
    protein: 36,
    carbs: 32,
    fat: 22,
    prepTime: 30,
    imageQuery: "salmon",
    ingredients: ["150g salmon fillet", "asparagus", "cherry tomatoes", "1 cup wild rice", "lemon", "olive oil", "dill"],
    instructions: [
      "Cook rice per package directions.",
      "Roast vegetables at 400°F for 20 minutes with olive oil.",
      "Season salmon with dill and lemon, bake 12 minutes.",
      "Plate together and drizzle with lemon.",
    ],
  },
  {
    id: "bal-2",
    name: "Turkey & Veggie Stir Fry",
    category: "balanced",
    calories: 430,
    protein: 34,
    carbs: 38,
    fat: 14,
    prepTime: 20,
    imageQuery: "stir fry",
    ingredients: ["200g ground turkey", "broccoli", "snap peas", "carrots", "1 cup jasmine rice", "teriyaki sauce", "sesame seeds"],
    instructions: [
      "Cook rice.",
      "Brown turkey in a wok over high heat.",
      "Add vegetables and stir fry 4 minutes.",
      "Add teriyaki sauce and toss.",
      "Serve over rice, top with sesame seeds.",
    ],
  },
  {
    id: "bal-3",
    name: "Chickpea & Spinach Curry",
    category: "balanced",
    calories: 420,
    protein: 18,
    carbs: 58,
    fat: 14,
    prepTime: 25,
    imageQuery: "dal",
    ingredients: ["1 can chickpeas", "2 cups spinach", "1 can coconut milk", "onion", "garlic", "curry powder", "garam masala", "basmati rice"],
    instructions: [
      "Sauté onion and garlic with curry powder.",
      "Add drained chickpeas and coconut milk.",
      "Simmer 15 minutes, add spinach and wilt.",
      "Serve over basmati rice.",
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  "high-protein": "High Protein",
  "high-carb": "High Carb",
  "low-calorie": "Low Calorie",
  "balanced": "Balanced",
  "ai-generated": "AI Generated",
};

export const CATEGORY_COLORS: Record<string, string> = {
  "high-protein": "bg-red-100 text-red-700 border-red-200",
  "high-carb": "bg-yellow-100 text-yellow-700 border-yellow-200",
  "low-calorie": "bg-green-100 text-green-700 border-green-200",
  "balanced": "bg-blue-100 text-blue-700 border-blue-200",
  "ai-generated": "bg-purple-100 text-purple-700 border-purple-200",
};
