import type { Meal, MealCategory } from "../types";

export const MEAL_LIBRARY: Meal[] = [
  {
    id: "grilled-chicken-bowl",
    name: "Grilled Chicken Bowl",
    category: "high-protein",
    calories: 480,
    protein: 45,
    carbs: 38,
    fat: 12,
    prepTime: 25,
    imageQuery: "chicken",
    ingredients: [
      "200g chicken breast",
      "1 cup brown rice",
      "1 cup broccoli florets",
      "2 tbsp olive oil",
      "1 tsp garlic powder",
      "Salt & pepper",
    ],
    instructions: [
      "Season chicken with garlic powder, salt, and pepper.",
      "Grill chicken 6-7 min per side until cooked through.",
      "Cook rice according to package directions.",
      "Steam broccoli for 4-5 minutes.",
      "Assemble bowl and drizzle with olive oil.",
    ],
  },
  {
    id: "salmon-quinoa",
    name: "Salmon & Quinoa",
    category: "high-protein",
    calories: 520,
    protein: 42,
    carbs: 35,
    fat: 18,
    prepTime: 30,
    imageQuery: "salmon",
    ingredients: [
      "180g salmon fillet",
      "3/4 cup quinoa",
      "2 cups spinach",
      "1 lemon",
      "2 tbsp olive oil",
      "Dill, salt & pepper",
    ],
    instructions: [
      "Cook quinoa per package directions.",
      "Season salmon with dill, salt, pepper.",
      "Pan-sear salmon 4 min each side.",
      "Wilt spinach in the same pan.",
      "Plate with quinoa, top with lemon juice.",
    ],
  },
  {
    id: "greek-yogurt-parfait",
    name: "Greek Yogurt Parfait",
    category: "high-protein",
    calories: 320,
    protein: 28,
    carbs: 42,
    fat: 6,
    prepTime: 5,
    imageQuery: "yogurt",
    ingredients: [
      "1 cup Greek yogurt",
      "1/2 cup granola",
      "1/2 cup mixed berries",
      "1 tbsp honey",
      "1 tbsp chia seeds",
    ],
    instructions: [
      "Layer yogurt in a glass or bowl.",
      "Top with granola and berries.",
      "Drizzle honey and sprinkle chia seeds.",
    ],
  },
  {
    id: "turkey-wrap",
    name: "Turkey Avocado Wrap",
    category: "high-protein",
    calories: 430,
    protein: 35,
    carbs: 40,
    fat: 14,
    prepTime: 10,
    imageQuery: "wrap",
    ingredients: [
      "120g sliced turkey breast",
      "1 whole wheat tortilla",
      "1/2 avocado",
      "Lettuce & tomato",
      "1 tsp Dijon mustard",
    ],
    instructions: [
      "Spread mustard on tortilla.",
      "Layer turkey, sliced avocado, lettuce, and tomato.",
      "Roll tightly and cut in half.",
    ],
  },
  {
    id: "oatmeal-banana",
    name: "Banana Oatmeal",
    category: "high-carb",
    calories: 380,
    protein: 12,
    carbs: 68,
    fat: 7,
    prepTime: 10,
    imageQuery: "oatmeal",
    ingredients: [
      "1 cup rolled oats",
      "1 banana",
      "1 tbsp peanut butter",
      "1 cup almond milk",
      "1 tbsp honey",
      "Cinnamon",
    ],
    instructions: [
      "Cook oats in almond milk for 5 minutes.",
      "Slice banana and stir half into oats.",
      "Top with remaining banana, peanut butter, honey, and cinnamon.",
    ],
  },
  {
    id: "pasta-marinara",
    name: "Pasta Marinara",
    category: "high-carb",
    calories: 450,
    protein: 16,
    carbs: 78,
    fat: 8,
    prepTime: 20,
    imageQuery: "pasta",
    ingredients: [
      "200g whole wheat pasta",
      "1 cup marinara sauce",
      "2 cloves garlic",
      "1 tbsp olive oil",
      "Fresh basil",
      "Parmesan cheese",
    ],
    instructions: [
      "Cook pasta al dente.",
      "Sauté garlic in olive oil.",
      "Add marinara and simmer 5 minutes.",
      "Toss with pasta, top with basil and parmesan.",
    ],
  },
  {
    id: "sweet-potato-lentil",
    name: "Sweet Potato Lentil Curry",
    category: "high-carb",
    calories: 410,
    protein: 18,
    carbs: 65,
    fat: 9,
    prepTime: 35,
    imageQuery: "curry",
    ingredients: [
      "1 large sweet potato",
      "1 cup red lentils",
      "1 can coconut milk",
      "1 tbsp curry powder",
      "1 onion",
      "2 cloves garlic",
    ],
    instructions: [
      "Dice sweet potato and onion.",
      "Sauté onion and garlic until soft.",
      "Add curry powder, lentils, sweet potato, and coconut milk.",
      "Simmer 25 minutes until lentils are tender.",
    ],
  },
  {
    id: "zucchini-noodles",
    name: "Zucchini Noodles with Pesto",
    category: "low-calorie",
    calories: 220,
    protein: 10,
    carbs: 18,
    fat: 14,
    prepTime: 15,
    imageQuery: "zucchini",
    ingredients: [
      "2 medium zucchini",
      "3 tbsp pesto sauce",
      "Cherry tomatoes",
      "Parmesan",
      "Pine nuts",
    ],
    instructions: [
      "Spiralize zucchini into noodles.",
      "Sauté noodles 2-3 minutes.",
      "Toss with pesto and halved cherry tomatoes.",
      "Top with parmesan and pine nuts.",
    ],
  },
  {
    id: "veggie-stir-fry",
    name: "Veggie Stir-Fry",
    category: "low-calorie",
    calories: 240,
    protein: 12,
    carbs: 32,
    fat: 7,
    prepTime: 20,
    imageQuery: "stir fry",
    ingredients: [
      "Broccoli, bell pepper, snap peas",
      "200g firm tofu",
      "2 tbsp soy sauce",
      "1 tsp sesame oil",
      "1 tsp ginger",
      "1 clove garlic",
    ],
    instructions: [
      "Press and cube tofu, pan-fry until golden.",
      "Stir-fry vegetables with garlic and ginger.",
      "Add tofu, soy sauce, and sesame oil.",
      "Serve as-is or over cauliflower rice.",
    ],
  },
  {
    id: "egg-white-omelette",
    name: "Egg White Omelette",
    category: "low-calorie",
    calories: 190,
    protein: 22,
    carbs: 8,
    fat: 6,
    prepTime: 10,
    imageQuery: "omelette",
    ingredients: [
      "4 egg whites",
      "Spinach",
      "Mushrooms",
      "1/4 onion",
      "1 tbsp feta cheese",
      "Salt & pepper",
    ],
    instructions: [
      "Sauté vegetables until soft.",
      "Whisk egg whites with salt and pepper.",
      "Pour over vegetables in pan.",
      "Cook until set, fold and top with feta.",
    ],
  },
  {
    id: "chicken-dal",
    name: "Chicken Dal",
    category: "balanced",
    calories: 390,
    protein: 32,
    carbs: 44,
    fat: 10,
    prepTime: 40,
    imageQuery: "dal",
    ingredients: [
      "150g chicken breast",
      "1/2 cup yellow lentils",
      "1 can diced tomatoes",
      "1 tsp turmeric",
      "1 tsp cumin",
      "1 tsp garam masala",
    ],
    instructions: [
      "Cook lentils until soft.",
      "Dice and cook chicken until done.",
      "Add tomatoes and spices, simmer 10 minutes.",
      "Combine chicken with dal and serve.",
    ],
  },
  {
    id: "salmon-veggie",
    name: "Baked Salmon with Veggies",
    category: "balanced",
    calories: 430,
    protein: 36,
    carbs: 28,
    fat: 18,
    prepTime: 30,
    imageQuery: "baked salmon",
    ingredients: [
      "170g salmon fillet",
      "Asparagus spears",
      "Cherry tomatoes",
      "1 tbsp olive oil",
      "Lemon, garlic, dill",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Toss veggies in olive oil, season.",
      "Place salmon and veggies on a sheet pan.",
      "Bake 15-18 minutes until salmon flakes.",
    ],
  },
  {
    id: "black-bean-bowl",
    name: "Black Bean Rice Bowl",
    category: "balanced",
    calories: 420,
    protein: 18,
    carbs: 62,
    fat: 10,
    prepTime: 20,
    imageQuery: "rice bowl",
    ingredients: [
      "1 can black beans",
      "1 cup brown rice",
      "1 avocado",
      "Salsa",
      "1 lime",
      "Cilantro, cumin",
    ],
    instructions: [
      "Cook rice.",
      "Heat black beans with cumin.",
      "Assemble bowl with rice, beans, sliced avocado.",
      "Top with salsa, lime juice, and cilantro.",
    ],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  "high-protein": "High Protein",
  "high-carb": "High Carb",
  "low-calorie": "Low Calorie",
  balanced: "Balanced",
};

export const CATEGORY_COLORS: Record<string, string> = {
  "high-protein": "#ef4444",
  "high-carb": "#f59e0b",
  "low-calorie": "#3b82f6",
  balanced: "#10b981",
};
